import { Command } from 'commander';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

type GoalCorrection = {
  retraction_anchor?: unknown;
  retraction_source?: unknown;
  false_claims_in_this_file?: unknown;
  true_baseline?: unknown;
  corrected_disposition?: unknown;
};

function correctionLines(data: Record<string, unknown>): string[] {
  const entries = Object.entries(data)
    .filter(([key, value]) => key.includes('_correction_') && value !== null && typeof value === 'object')
    .sort(([a], [b]) => a.localeCompare(b));

  return entries.flatMap(([key, raw]) => {
    const correction = raw as GoalCorrection;
    const dateMatch = key.match(/(\d{4}_\d{2}_\d{2})$/);
    const date = dateMatch ? dateMatch[1].replaceAll('_', '-') : 'preserved';
    const lines = [`> ## ⚠️ CORRECTION — ${date} (append-only; do not delete)`];

    if (typeof correction.retraction_anchor === 'string') {
      const source = typeof correction.retraction_source === 'string'
        ? ` (${correction.retraction_source})`
        : '';
      lines.push(`> **Retraction anchor:** \`${correction.retraction_anchor}\`${source}`);
    }

    if (Array.isArray(correction.false_claims_in_this_file)) {
      correction.false_claims_in_this_file
        .filter((claim): claim is string => typeof claim === 'string')
        .forEach((claim) => lines.push(`> - ${claim}`));
    }

    if (typeof correction.true_baseline === 'string') {
      lines.push(`> **True baseline:** ${correction.true_baseline}`);
    }
    if (typeof correction.corrected_disposition === 'string') {
      lines.push(`> **Corrected disposition:** ${correction.corrected_disposition}`);
    }

    return [...lines, ''];
  });
}

export function renderGoalsMarkdown(
  data: Record<string, unknown>,
  options: { agent: string; org: string },
): string {
  const goals = Array.isArray(data.goals) ? (data.goals as Array<string | { title: string }>) : [];
  const focus = typeof data.focus === 'string' ? data.focus : '';
  const bottleneck = typeof data.bottleneck === 'string' ? data.bottleneck : '';
  const updatedAt = typeof data.updated_at === 'string' ? data.updated_at : new Date().toISOString();
  const updatedBy = typeof data.updated_by === 'string' ? data.updated_by : '';

  const lines: string[] = [
    '# Goals',
    '',
    '> Auto-generated from goals.json. Do not edit this file directly.',
    `> To regenerate: \`cortextos goals generate-md --agent ${options.agent} --org ${options.org}\``,
    '',
    ...correctionLines(data),
    '## Focus',
    focus || '(not set — check with your orchestrator)',
    '',
    '## Goals',
  ];

  if (goals.length === 0) {
    lines.push('(none set — message your orchestrator to request today\'s goals)');
  } else {
    goals.forEach((g, i) => {
      const title = typeof g === 'string' ? g : (g as { title: string }).title;
      lines.push(`${i + 1}. ${title}`);
    });
  }

  lines.push(
    '',
    '## Bottleneck',
    bottleneck || '(none)',
    '',
    '## Updated',
    updatedBy ? `${updatedAt} (by ${updatedBy})` : updatedAt,
    '',
  );

  return lines.join('\n');
}

export const goalsCommand = new Command('goals')
  .description('Manage goals.json and auto-generate GOALS.md for agents');

// cortextos goals generate-md --agent <name> --org <org>
goalsCommand
  .command('generate-md')
  .description('Regenerate GOALS.md from goals.json for an agent')
  .requiredOption('--agent <name>', 'Agent name')
  .requiredOption('--org <org>', 'Org name')
  .action((options: { agent: string; org: string }) => {
    const frameworkRoot = process.env.CTX_FRAMEWORK_ROOT || process.cwd();

    if (!/^[A-Za-z0-9_-]+$/.test(options.agent) || !/^[A-Za-z0-9_-]+$/.test(options.org)) {
      process.stderr.write('Error: agent and org must be alphanumeric/dash/underscore only\n');
      process.exit(1);
    }

    const agentDir = join(frameworkRoot, 'orgs', options.org, 'agents', options.agent);
    const goalsJsonPath = join(agentDir, 'goals.json');
    const goalsMdPath = join(agentDir, 'GOALS.md');

    if (!existsSync(goalsJsonPath)) {
      process.stderr.write(`goals.json not found at ${goalsJsonPath}\n`);
      process.exit(1);
    }

    let data: Record<string, unknown>;
    try {
      data = JSON.parse(readFileSync(goalsJsonPath, 'utf-8'));
    } catch {
      process.stderr.write(`Failed to parse goals.json for ${options.agent}\n`);
      process.exit(1);
    }

    writeFileSync(goalsMdPath, renderGoalsMarkdown(data, options), 'utf-8');
    console.log(`Generated GOALS.md for ${options.agent}`);
  });
