import { execFile } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { promisify } from 'node:util';
import { describe, expect, it } from 'vitest';
import { createGoalManifest } from '../../src/goals/goal-manifest.js';
import { DEFAULT_GOAL_CONFIG, type GoalRun } from '../../src/goals/goal-run.js';
import { GoalRunStore } from '../../src/goals/goal-run-store.js';
import { GoalRunner } from '../../src/goals/goal-runner.js';
import { GoalThreadManager } from '../../src/goals/goal-thread-manager.js';
import { CodexAppServerPTY } from '../../src/pty/codex-app-server-pty.js';
const execFileAsync = promisify(execFile);
const waitFor = async (predicate: () => Promise<boolean>, label: string, timeoutMs = 5_000): Promise<void> => { const started = Date.now(); while (Date.now() - started < timeoutMs) { if (await predicate()) return; await new Promise((resolve) => setTimeout(resolve, 20)); } throw new Error(`timed out waiting for ${label}`); };
const create = (): GoalRun => { const objective = '# Program\n- Alloi\n- Calasia\n- Goal\n- Fleet\n- SEIU\n- Close revisions'; const manifest = createGoalManifest(objective); return { schemaVersion: 3, id: 'mission', agentName: 'agent', goal: objective, repo: process.cwd(), state: 'queued', manifest, itemProgress: manifest.boards[0]!.items.map((item) => ({ itemId: item.id, status: 'runnable', phase: 'implementation', cycle: 1, attempt: 0, evidenceReceipts: [], reviewReceipts: [], findings: [], updatedAt: new Date(0).toISOString() })), schedulingCursor: 0, attempt: 0, maxAttempts: 3, acceptanceChecks: [], artifacts: [], events: [], createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() }; };
describe('goal control-plane process recovery', () => {
  it('preserves exact six-item manifest and reclaims crash once only after expiry', async () => { const root = mkdtempSync(`${tmpdir()}/goal-process-v3-`); try { const config = { ...DEFAULT_GOAL_CONFIG, leaseTtlMs: 100 }; const store = new GoalRunStore(root, config); await store.initialize(); await store.create(create()); const source = new URL('../../src/goals/goal-run-store.ts', import.meta.url).pathname; const program = `import m from ${JSON.stringify(source)};const s=new m.GoalRunStore(process.argv[1],${JSON.stringify(config)});const r=await s.claimEligible('agent','mission',process.argv[2],Number(process.argv[3]));console.log(r.kind)`; const child = async (owner: string, now: number) => (await execFileAsync(process.execPath, ['--import', 'tsx', '--input-type=module', '--eval', program, root, owner, String(now)])).stdout.trim(); expect(await child('a', 0)).toBe('claimed'); expect(await child('b', 99)).toBe('not_eligible'); expect(await child('b', 100)).toBe('claimed'); expect(await child('c', 101)).toBe('not_eligible'); const persisted = await store.get('agent', 'mission'); expect(persisted?.manifest?.boards[0]?.items).toHaveLength(6); expect(persisted?.manifest?.objectiveVerbatim).toBe(create().goal); } finally { rmSync(root, { recursive: true, force: true }); } });
  it('a fresh real PTY initialization recovers an expired claimed run without inbound input', async () => { const root = mkdtempSync(`${tmpdir()}/goal-real-pty-restart-`); const stateRoot = join(root, 'state', 'agent'); const run = create(); run.id = 'restart'; run.goal = 'restart'; run.manifest = createGoalManifest('restart', ['proof']); run.itemProgress = [{ itemId: 'item-001', status: 'runnable', phase: 'implementation', cycle: 1, attempt: 0, evidenceReceipts: [], reviewReceipts: [], findings: [], updatedAt: new Date(0).toISOString() }]; run.acceptanceChecks = [{ id: 'proof', command: [process.execPath, '-e', 'process.exit(0)'], timeoutMs: 1000, required: true }]; const store = new GoalRunStore(stateRoot, DEFAULT_GOAL_CONFIG); await store.initialize(); await store.create(run); expect((await store.claimEligible('agent', 'restart', 'crashed', 0)).kind).toBe('claimed'); const pty: any = new CodexAppServerPTY({ ctxRoot: root, agentName: 'agent', agentDir: root, projectRoot: root, frameworkRoot: root, instanceId: 'test', org: 'test' }, { name: 'agent', working_directory: process.cwd() }); let thread = 0; let turn = 0; pty.request = async (method: string, params: any) => { if (method === 'thread/start') return { result: { thread: { id: `thread-${++thread}` } } }; if (method === 'turn/start') { const turnId = `turn-${++turn}`; const review = params.input[0].text.includes('Independently review'); const report = review ? { kind: 'review_report', itemId: 'item-001', cycle: 1, decision: 'approved', summary: 'ok' } : { kind: 'implementation_report', itemId: 'item-001', cycle: 1, status: 'completed', summary: 'done' }; setImmediate(() => { pty.handleRpcMessage({ method: 'item/completed', params: { threadId: params.threadId, turnId, item: { type: 'agentMessage', text: JSON.stringify(report), threadId: params.threadId, turnId } } }); pty.handleRpcMessage({ method: 'turn/completed', params: { threadId: params.threadId, turnId, turn: { id: turnId, threadId: params.threadId, status: 'completed' } } }); }); return { result: { turn: { id: turnId } } }; } return { result: {} }; }; try { await pty.initializeGoalIntegration(); await pty.goalTickPromise; expect((await store.get('agent', 'restart'))?.state).toBe('done'); } finally { await pty.kill(); rmSync(root, { recursive: true, force: true }); } });
  it('blocked sibling and reviewer findings survive separate runner instances', async () => { const root = mkdtempSync(`${tmpdir()}/goal-runner-restarts-`); let now = Date.now(); const config = { ...DEFAULT_GOAL_CONFIG, retryDelayMs: 1, retryMaxDelayMs: 1 }; const run = create(); run.acceptanceChecks = [{ id: 'proof', command: [process.execPath, '-e', 'process.exit(0)'], timeoutMs: 1000, required: true }]; run.manifest = createGoalManifest('# B\n- One\n- Two', ['proof']); run.goal = run.manifest.objectiveVerbatim; run.itemProgress = run.manifest.boards[0]!.items.map((item) => ({ itemId: item.id, status: 'runnable', phase: 'implementation', cycle: 1, attempt: 0, evidenceReceipts: [], reviewReceipts: [], findings: [], updatedAt: new Date(now).toISOString() })); const store = new GoalRunStore(root, config); await store.initialize(); await store.create(run); let reviewOne = 0; const api = { createThread: async ({ role }: any) => ({ id: `${role}-${Math.random()}` }), resumeThread: async () => {}, setThreadGoal: async () => {}, dispatchPrompt: async (_thread: string, prompt: string) => { const itemId = /(?:Item |review )(item-\d+)/i.exec(prompt)?.[1]!; const cycle = Number(/(?:Cycle: |cycle )(\d+)/i.exec(prompt)?.[1] ?? 1); if (itemId === 'item-001' && cycle === 1 && !prompt.includes('Independently review')) return { outcome: 'failed' as const, blocker: { kind: 'credential' as const, summary: 'token', source: 'codex_turn' as const } }; if (prompt.includes('Independently review') && itemId === 'item-002') { reviewOne += 1; return { outcome: 'completed' as const, report: reviewOne === 1 ? { kind: 'review_report', itemId, cycle, decision: 'changes_requested', summary: 'fix', findings: [{ summary: 'restart finding' }] } : { kind: 'review_report', itemId, cycle, decision: 'approved', summary: 'ok' } }; } return { outcome: 'completed' as const, report: { kind: 'implementation_report', itemId, cycle, status: 'completed', summary: 'done' } }; } }; try { await new GoalRunner(store, config, new GoalThreadManager(api), () => ['agent'], () => now).processTick(); await new GoalRunner(store, config, new GoalThreadManager(api), () => ['agent'], () => now).processTick(); expect((await store.get('agent', 'mission'))?.itemProgress?.[1]?.cycle).toBe(2); now += 2; await new GoalRunner(store, config, new GoalThreadManager(api), () => ['agent'], () => now).processTick(); const persisted = await store.get('agent', 'mission'); expect(persisted?.itemProgress?.map((item) => item.status)).toEqual(['waiting', 'done']); expect(persisted?.itemProgress?.[1]?.findings.some((finding) => finding.summary === 'restart finding')).toBe(true); } finally { rmSync(root, { recursive: true, force: true }); } });
  it.skipIf(process.platform === 'win32')('PTY-owned GoalRunner kills a stdio-ignored resistant verifier grandchild and releases its persisted lease', async () => {
    const root = mkdtempSync(`${tmpdir()}/goal-runner-pty-kill-`); const stateRoot = join(root, 'state', 'agent'); const pidFile = join(root, 'pids.json');
    const previousTick = process.env.CXR_GOAL_TICK_INTERVAL_MS; process.env.CXR_GOAL_TICK_INTERVAL_MS = '60000';
    const source = `const {spawn}=require('node:child_process');const fs=require('node:fs');const child=spawn(process.execPath,['-e',"process.on('SIGTERM',()=>{});setInterval(()=>{},1000)"],{stdio:'ignore'});process.on('SIGTERM',()=>process.exit(0));fs.writeFileSync(${JSON.stringify(pidFile)},JSON.stringify({parent:process.pid,grandchild:child.pid}));setInterval(()=>{},1000)`;
    const objective = 'finish after verifier shutdown'; const manifest = createGoalManifest(objective, ['resistant']); const now = new Date().toISOString();
    const run: GoalRun = { schemaVersion: 3, id: 'kill-run', agentName: 'agent', goal: objective, repo: process.cwd(), state: 'queued', manifest, itemProgress: [{ itemId: 'item-001', status: 'done', phase: 'review', cycle: 1, attempt: 0, evidenceReceipts: [], reviewReceipts: [], findings: [], updatedAt: now }], schedulingCursor: 0, attempt: 0, maxAttempts: 3, acceptanceChecks: [{ id: 'resistant', command: [process.execPath, '-e', source], timeoutMs: 300, required: true }], artifacts: [], events: [], createdAt: now, updatedAt: now };
    const store = new GoalRunStore(stateRoot, DEFAULT_GOAL_CONFIG); await store.initialize(); await store.create(run);
    const pty: any = new CodexAppServerPTY({ ctxRoot: root, agentName: 'agent', agentDir: root, projectRoot: root, frameworkRoot: root, instanceId: 'test', org: 'test' }, { name: 'agent', working_directory: process.cwd() });
    pty.request = async () => ({ result: {} });
    try {
      await pty.initializeGoalIntegration(); await waitFor(async () => (await store.get('agent', run.id))?.state === 'retry_wait', 'verifier retry and lease release');
      const persisted = await store.get('agent', run.id);
      expect(persisted?.state).toBe('retry_wait');
      expect(persisted?.leaseOwner).toBeUndefined(); expect(persisted?.leaseToken).toBeUndefined(); expect(persisted?.leaseExpiresAt).toBeUndefined();
      const pids = JSON.parse(readFileSync(pidFile, 'utf8')) as { parent: number; grandchild: number };
      for (const pid of [pids.parent, pids.grandchild]) expect(() => process.kill(pid, 0)).toThrow();
    } finally {
      await pty.kill(); if (previousTick === undefined) delete process.env.CXR_GOAL_TICK_INTERVAL_MS; else process.env.CXR_GOAL_TICK_INTERVAL_MS = previousTick; rmSync(root, { recursive: true, force: true });
    }
  }, 10_000);
});
