import { randomUUID } from 'node:crypto';
import type { GoalConfig, GoalRun } from '../types/goal-run.js';
import { GoalEventLogger } from './goal-event-logger.js';
import { GoalLeaseProtocol } from './goal-lease-protocol.js';
import { GoalRunStore } from './goal-run-store.js';
import { GoalStateMachine } from './goal-state-machine.js';
import { GoalThreadManager } from './goal-thread-manager.js';
import { GoalVerifier } from './goal-verifier.js';

export class GoalRunner {
  private readonly runnerId = `runner-${randomUUID()}`; private readonly verifier: GoalVerifier;
  constructor(private readonly store: GoalRunStore, private readonly config: GoalConfig, private readonly threadManager: GoalThreadManager) { this.verifier = new GoalVerifier(config); }
  async processTick(agentName: string): Promise<void> { for (const candidate of await this.findCandidateRuns(agentName)) { try { await this.processRun(candidate); } catch (error) { if (candidate.leaseToken) await this.logErrorEvent(candidate, error).catch(() => {}); } } }
  private async findCandidateRuns(agentName: string): Promise<GoalRun[]> { const now = Date.now(); return (await this.store.list(agentName)).filter(run => run.state === 'queued' || (run.state === 'retry_wait' && now >= this.retryAt(run).getTime()) || (!GoalStateMachine.isTerminal(run.state) && GoalLeaseProtocol.isExpired(run))); }
  private async processRun(run: GoalRun): Promise<void> { const retrying = run.state === 'retry_wait'; const claimed = await this.claimRun(run); if (!claimed) return; try { if (retrying) await this.executeRetry(claimed); else await this.executeClaimed(claimed); } finally { const latest = await this.store.get(claimed.agentName, claimed.id); if (latest?.leaseToken === claimed.leaseToken) await this.store.update(claimed.agentName, claimed.id, claimed.leaseToken!, GoalLeaseProtocol.clear); } }
  private async claimRun(run: GoalRun): Promise<GoalRun | null> { const lease = GoalLeaseProtocol.generateLease(this.runnerId); try { return await this.store.update(run.agentName, run.id, run.leaseToken ?? '', current => { if (GoalStateMachine.isTerminal(current.state)) throw new Error('Run is terminal'); if (current.leaseToken && !GoalLeaseProtocol.isExpired(current)) throw new Error('Run is already leased'); const now = new Date().toISOString(); const claimed = current.state === 'queued' || current.state === 'retry_wait' ? GoalStateMachine.transition(current, 'claimed', { runnerId: this.runnerId }) : { ...current, state: 'claimed' as const, updatedAt: now, events: [...current.events, { id: randomUUID(), type: 'state_changed' as const, timestamp: now, data: { from: current.state, to: 'claimed', runnerId: this.runnerId, reclaimed: true } }] }; return { ...claimed, ...lease, events: [...claimed.events, { id: randomUUID(), type: 'claimed', timestamp: now, data: { runnerId: this.runnerId } }] }; }); } catch { return null; } }
  private async executeClaimed(run: GoalRun): Promise<void> { const token = run.leaseToken!; let current = await this.store.update(run.agentName, run.id, token, value => GoalStateMachine.transition(value, 'running')); if (!current.threadId) { const threadId = await this.threadManager.createThread(current); current = await this.store.update(run.agentName, run.id, token, value => ({ ...value, threadId, updatedAt: new Date().toISOString() })); } else await this.threadManager.resumeThread(current.threadId); await this.threadManager.setThreadGoal(current.threadId!, current.goal); await GoalEventLogger.logEvent(this.store, run.agentName, run.id, token, { type: 'turn_started', data: { threadId: current.threadId } }); await this.threadManager.dispatchPrompt(current.threadId!, this.buildDispatchPrompt(current)); await GoalEventLogger.logEvent(this.store, run.agentName, run.id, token, { type: 'turn_completed', data: { threadId: current.threadId } }); current = await this.store.update(run.agentName, run.id, token, value => GoalStateMachine.transition(value, 'verifying')); await GoalEventLogger.logEvent(this.store, run.agentName, run.id, token, { type: 'verifying' }); const verified = await this.verifier.verify(current); current = await this.store.update(run.agentName, run.id, token, value => ({ ...value, artifacts: [...value.artifacts, ...verified.artifacts], updatedAt: new Date().toISOString() })); for (const result of verified.results) await GoalEventLogger.logEvent(this.store, run.agentName, run.id, token, { type: result.passed ? 'check_passed' : 'check_failed', data: result }); if (verified.passed) await this.store.update(run.agentName, run.id, token, value => GoalStateMachine.transition(value, 'done')); else await this.failOrRetry(current, token, 'Acceptance checks failed'); }
  private async executeRetry(run: GoalRun): Promise<void> { const token = run.leaseToken!; await this.store.update(run.agentName, run.id, token, value => ({ ...value, attempt: value.attempt + 1, updatedAt: new Date().toISOString() })); const current = await this.store.get(run.agentName, run.id); if (current) await this.executeClaimed(current); }
  private async failOrRetry(run: GoalRun, token: string, reason: string): Promise<void> { const lower = reason.toLowerCase(); const state = /approval|human|permission|credential/.test(lower) ? 'needs_human' : 'retry_wait'; await this.store.update(run.agentName, run.id, token, value => GoalStateMachine.transition(value, state, { reason })); }
  private retryAt(run: GoalRun): Date { return new Date(new Date(run.updatedAt).getTime() + Math.min(this.config.retryDelayMs * 2 ** run.attempt, this.config.retryMaxDelayMs)); }
  private buildDispatchPrompt(run: GoalRun): string { const checks = run.acceptanceChecks.map(check => `- ${check.required ? '[REQUIRED]' : '[OPTIONAL]'} ${check.command.join(' ')} (timeout: ${check.timeoutMs}ms)`).join('\n'); return `You are working on goal: "${run.goal}"\n\nThis is durable attempt ${run.attempt + 1}; recoverable failures retry until acceptance checks pass.\n\nACCEPTANCE CHECKS:\n${checks}\n\nARTIFACT LOCATION: ${run.repo}\n\nINVARIANT: Do not report completion until all required acceptance checks pass.\nIf blocked, name the concrete human/approval dependency.\nOtherwise, continue by taking the next safe implementation or verification action.\n\nContinue working until the goal is complete or you hit a blocker.`; }
  private async logErrorEvent(run: GoalRun, error: unknown): Promise<void> { await GoalEventLogger.logEvent(this.store, run.agentName, run.id, run.leaseToken!, { type: 'error', data: { error: error instanceof Error ? error.message : String(error) } }); }
}
