import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { describe, expect, it } from 'vitest';
import { createGoalManifest } from '../../../src/goals/goal-manifest.js';
import { currentGitCommit, DEFAULT_GOAL_CONFIG, selectGoalAcceptanceProfile, type GoalRun } from '../../../src/goals/goal-run.js';
import { GoalRunStore } from '../../../src/goals/goal-run-store.js';
import { GoalRunner } from '../../../src/goals/goal-runner.js';
import { GoalThreadManager } from '../../../src/goals/goal-thread-manager.js';
const config = { ...DEFAULT_GOAL_CONFIG, retryDelayMs: 1, retryMaxDelayMs: 1, leaseTtlMs: 10_000 };
const makeRun = (objective: string): GoalRun => { const checks = [{ id: 'proof', command: [process.execPath, '-e', 'process.exit(0)'], timeoutMs: 1000, required: true }]; const manifest = createGoalManifest(objective, ['proof']); return { schemaVersion: 3, id: 'run', agentName: 'agent', goal: objective, repo: process.cwd(), state: 'queued', manifest, itemProgress: manifest.boards.flatMap((board) => board.items).map((item) => ({ itemId: item.id, status: 'runnable', phase: 'implementation', cycle: 1, attempt: 0, evidenceReceipts: [], reviewReceipts: [], findings: [], updatedAt: new Date(0).toISOString() })), schedulingCursor: 0, attempt: 0, maxAttempts: 2, acceptanceChecks: checks, artifacts: [], events: [], createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() }; };
const setup = async (run: GoalRun, api: any, clock: () => number = () => 100) => { const root = mkdtempSync(`${tmpdir()}/goal-runner-v3-`); const store = new GoalRunStore(root, config); await store.initialize(); await store.create(run); return { root, store, runner: new GoalRunner(store, config, new GoalThreadManager(api), () => ['agent'], clock) }; };
const baseApi = (dispatchPrompt: any) => { let id = 0; return { createThread: async ({ role }: any) => ({ id: `${role}-${++id}` }), resumeThread: async () => {}, setThreadGoal: async () => {}, dispatchPrompt }; };
describe('GoalRunner multi-item control plane', () => {
  it('requires a fresh current-commit observed baseline and rejects fabricated inventory', () => { const now = Date.now(); const date = new Date(now).toISOString(); const commit = currentGitCommit(process.cwd()); const observation = { date, commit, command: 'npm test', exitCode: 1, failures: ['next/server'] }; const waiver = { date, commit, command: 'npm test', owner: 'larry', reason: 'deps', failures: ['next/server'] }; const env = { CXR_GOAL_ACCEPTANCE_PROFILE: 'repository-full', CXR_GOAL_BASELINE_OBSERVATION: JSON.stringify(observation), CXR_GOAL_BASELINE_WAIVER: JSON.stringify(waiver) }; expect(selectGoalAcceptanceProfile({}, config).name).toBe('goal-focused'); expect(selectGoalAcceptanceProfile(env, config, process.cwd(), now).baselineWaiver?.failures).toEqual(['next/server']); for (const bad of [{ ...observation, date: new Date(0).toISOString() }, { ...observation, date: '2999-01-01T00:00:00.000Z' }, { ...observation, commit: 'bogus' }]) expect(() => selectGoalAcceptanceProfile({ ...env, CXR_GOAL_BASELINE_OBSERVATION: JSON.stringify(bad) }, config, process.cwd(), now)).toThrow('baseline rejected'); expect(() => selectGoalAcceptanceProfile({ ...env, CXR_GOAL_BASELINE_WAIVER: JSON.stringify({ ...waiver, failures: ['fabricated'] }) }, config, process.cwd(), now)).toThrow('observed failure inventory'); const greenObservation = { date, commit, command: 'npm test', exitCode: 0, failures: [] }; expect(selectGoalAcceptanceProfile({ CXR_GOAL_ACCEPTANCE_PROFILE: 'repository-full', CXR_GOAL_BASELINE_OBSERVATION: JSON.stringify(greenObservation), CXR_GOAL_BASELINE_GREEN: JSON.stringify({ date, commit, command: 'npm test' }) }, config, process.cwd(), now).baselineGreen?.commit).toBe(commit); });
  it('lets a runnable sibling finish while item one waits for a credential', async () => {
    let first = true; const run = makeRun('# Boards\n- One\n- Two'); const { root, store, runner } = await setup(run, baseApi(async (_thread: string, prompt: string) => { const item = /Item (item-\d+)/.exec(prompt)?.[1] ?? /review (item-\d+)/.exec(prompt)?.[1]; const cycle = Number(/(?:Cycle: |cycle )(\d+)/i.exec(prompt)?.[1] ?? 1); if (item === 'item-001' && first) { first = false; return { outcome: 'failed', blocker: { kind: 'credential', summary: 'token', source: 'codex_turn' } }; } return { outcome: 'completed', report: prompt.includes('Independently review') ? { kind: 'review_report', itemId: item, cycle, decision: 'approved', summary: 'ok' } : { kind: 'implementation_report', itemId: item, cycle, status: 'completed', summary: 'done' } }; }));
    try { await runner.processTick(); expect((await store.get('agent', 'run'))?.state).toBe('queued'); await runner.processTick(); const persisted = await store.get('agent', 'run'); expect(persisted?.itemProgress?.map((item) => item.status)).toEqual(['waiting', 'done']); expect(persisted?.state).toBe('needs_human'); } finally { rmSync(root, { recursive: true, force: true }); }
  });
  it('rejects planning-only output and keeps it durable', async () => { const run = makeRun('one'); const { root, store, runner } = await setup(run, baseApi(async () => ({ outcome: 'completed', report: { kind: 'implementation_report', itemId: 'item-001', cycle: 1, status: 'planning_only', summary: 'plan' } }))); try { await runner.processTick(); const persisted = await store.get('agent', 'run'); expect(persisted?.state).toBe('retry_wait'); expect(persisted?.itemProgress?.[0]?.status).not.toBe('done'); } finally { rmSync(root, { recursive: true, force: true }); } });
  it('keeps recoverable item work durable past the former attempt cap', async () => { const run = makeRun('one'); run.attempt = 7; run.itemProgress![0]!.attempt = 7; const { root, store, runner } = await setup(run, baseApi(async () => ({ outcome: 'completed', report: { kind: 'implementation_report', itemId: 'item-001', cycle: 1, status: 'planning_only', summary: 'still planning' } }))); try { await runner.processTick(); const persisted = await store.get('agent', 'run'); expect(persisted?.state).toBe('retry_wait'); expect(persisted?.itemProgress?.[0]?.attempt).toBe(8); } finally { rmSync(root, { recursive: true, force: true }); } });
  it('loops reviewer findings through a new cycle and then completes only with current evidence', async () => {
    let now = 100; let reviews = 0; const prompts: string[] = []; const run = makeRun('one'); const { root, store, runner } = await setup(run, baseApi(async (_thread: string, prompt: string) => { prompts.push(prompt); const cycle = Number(/(?:Cycle: |cycle )(\d+)/i.exec(prompt)?.[1] ?? 1); if (prompt.includes('Independently review')) { reviews += 1; return { outcome: 'completed', report: reviews === 1 ? { kind: 'review_report', itemId: 'item-001', cycle, decision: 'changes_requested', summary: 'fix', findings: [{ summary: 'missing edge case' }] } : { kind: 'review_report', itemId: 'item-001', cycle, decision: 'approved', summary: 'ok' } }; } return { outcome: 'completed', report: { kind: 'implementation_report', itemId: 'item-001', cycle, status: 'completed', summary: 'done' } }; }), () => now);
    try { await runner.processTick(); expect((await store.get('agent', 'run'))?.itemProgress?.[0]?.cycle).toBe(2); now += 2; await runner.processTick(); const persisted = await store.get('agent', 'run'); expect(persisted?.state).toBe('done'); expect(prompts.some((prompt) => prompt.includes('missing edge case'))).toBe(true); } finally { rmSync(root, { recursive: true, force: true }); }
  });
  it('sets the reviewer goal and sends the complete independent-review contract', async () => { const prompts: string[] = []; const goals: Array<[string, string]> = []; const run = makeRun('# Board\n- Exact item text'); run.artifacts = [{ id: 'implementation-artifact', type: 'custom', content: 'implementation proof', timestamp: new Date(0).toISOString() }]; run.itemProgress![0]!.findings = [{ id: 'prior-finding', itemId: 'item-001', cycle: 1, severity: 'blocking', summary: 'unresolved defect', resolved: false, timestamp: new Date(0).toISOString() }]; run.acceptanceChecks[0]!.command = [process.execPath, '-e', "process.stdout.write('check proof')"]; const api = baseApi(async (_thread: string, prompt: string) => { prompts.push(prompt); return { outcome: 'completed', report: prompt.includes('Independently review') ? { kind: 'review_report', itemId: 'item-001', cycle: 1, decision: 'approved', summary: 'ok' } : { kind: 'implementation_report', itemId: 'item-001', cycle: 1, status: 'completed', summary: 'implementation receipt summary', artifactIds: ['implementation-artifact'] } }; }); api.setThreadGoal = async (thread: string, goal: string) => { goals.push([thread, goal]); }; const { root, runner } = await setup(run, api); try { await runner.processTick(); const review = prompts.find((prompt) => prompt.includes('Independently review'))!; expect(review).toContain(`Overall objective (verbatim):\n${run.goal}`); expect(review).toContain('Item item-001 (verbatim):\nExact item text'); expect(review).toContain('implementation receipt summary'); expect(review).toContain('implementation proof'); expect(review).toContain('Evidence receipts:'); expect(review).toContain('Check receipts:'); expect(review).toContain('check proof'); expect(review).toContain('Unresolved findings:'); expect(review).toContain('unresolved defect'); expect(goals.some(([thread, goal]) => thread.startsWith('review-') && goal === run.goal)).toBe(true); } finally { rmSync(root, { recursive: true, force: true }); } });
  for (const boundary of ['last-item-persistence', 'final-check-persistence'] as const) it(`recovers verifying work after ${boundary}`, async () => { let now = 100; const run = makeRun('crash recovery'); const root = mkdtempSync(`${tmpdir()}/goal-runner-crash-`); const store: any = new GoalRunStore(root, config); await store.initialize(); await store.create(run); const api = baseApi(async (_thread: string, prompt: string) => ({ outcome: 'completed', report: prompt.includes('Independently review') ? { kind: 'review_report', itemId: 'item-001', cycle: 1, decision: 'approved', summary: 'ok' } : { kind: 'implementation_report', itemId: 'item-001', cycle: 1, status: 'completed', summary: 'done' } })); const claim = await store.claimEligible('agent', 'run', 'crashed-runner', now); if (claim.kind !== 'claimed') throw new Error('claim'); const originalUpdate = store.update.bind(store); let crashed = false; store.update = async (...args: any[]) => originalUpdate(args[0], args[1], args[2], (value: GoalRun) => { const next = args[3](value); const hit = boundary === 'last-item-persistence' ? next.state === 'verifying' && next.finalVerificationPassed === false : next.state === 'verifying' && next.finalVerificationPassed === true; if (hit && !crashed) { crashed = true; setImmediate(() => {}); } return next; }, args[4]).then((value: GoalRun) => { if (crashed) { crashed = false; throw new Error(`crash after ${boundary}`); } return value; }); try { await expect((new GoalRunner(store, config, new GoalThreadManager(api), () => ['agent'], () => now) as any).processClaim(claim.run)).rejects.toThrow(`crash after ${boundary}`); store.update = originalUpdate; const stranded = await store.get('agent', 'run'); expect(stranded?.state).toBe('verifying'); now = new Date(stranded!.leaseExpiresAt!).getTime(); await new GoalRunner(store, config, new GoalThreadManager(api), () => ['agent'], () => now).processTick(); expect((await store.get('agent', 'run'))?.state).toBe('done'); } finally { rmSync(root, { recursive: true, force: true }); } });
});
