import { describe, expect, it, vi } from 'vitest';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { CodexAppServerPTY } from '../../../src/pty/codex-app-server-pty.js';
import { createGoalManifest } from '../../../src/goals/goal-manifest.js';
import { DEFAULT_GOAL_CONFIG, type GoalRun } from '../../../src/goals/goal-run.js';
import { GoalRunStore } from '../../../src/goals/goal-run-store.js';
import { GoalRunner } from '../../../src/goals/goal-runner.js';
const env: any = { ctxRoot: '/tmp', agentName: 'agent', agentDir: '/tmp/agent', projectRoot: '/tmp/project', frameworkRoot: '/tmp/framework', instanceId: 'test', org: 'test' }; const agent: any = { name: 'agent', working_directory: process.cwd() };
describe('CodexAppServerPTY durable goal scheduler', () => {
  it('coalesces overlapping startup/timer/enqueue signals', async () => { const pty: any = new CodexAppServerPTY(env, agent); let release!: () => void; const gate = new Promise<void>((resolve) => { release = resolve; }); const processTick = vi.fn(async () => gate); pty.goalRunner = { processTick }; pty.signalGoalTick(); pty.signalGoalTick(); expect(processTick).toHaveBeenCalledTimes(1); release(); await new Promise((resolve) => setImmediate(resolve)); await new Promise((resolve) => setImmediate(resolve)); expect(processTick).toHaveBeenCalledTimes(2); await pty.stopGoalScheduler(); });
  it('awaits active work before RPC teardown and rejects future ticks', async () => { const pty: any = new CodexAppServerPTY(env, agent); let release!: () => void; const gate = new Promise<void>((resolve) => { release = resolve; }); const processTick = vi.fn(async () => gate); const close = vi.fn(); pty.goalRunner = { processTick }; pty._rpc = { close }; pty.signalGoalTick(); const stopping = pty.kill(); expect(close).not.toHaveBeenCalled(); release(); await stopping; expect(close).toHaveBeenCalledOnce(); pty.signalGoalTick(); expect(processTick).toHaveBeenCalledOnce(); });
  it('keeps native /goal fallback and parses resume without rewriting mentions', async () => { const pty: any = new CodexAppServerPTY(env, agent); pty.setGoal = vi.fn(async () => {}); await pty.handleGoalCommand('native'); expect(pty.setGoal).toHaveBeenCalledWith('native'); expect(pty.parseGoalCommand('/goal@bot resume run item-001')).toEqual({ type: 'resume', runId: 'run', itemId: 'item-001' }); });
  it('rejects /goal clear and /goal resume traversal and cannot cross agent ledgers', async () => { const root = mkdtempSync(`${tmpdir()}/goal-command-containment-`); const own = new GoalRunStore(join(root, 'state', 'agent'), DEFAULT_GOAL_CONFIG); const other = new GoalRunStore(join(root, 'state', 'other'), DEFAULT_GOAL_CONFIG); await own.initialize(); await other.initialize(); const manifest = createGoalManifest('waiting'); const foreign: GoalRun = { schemaVersion: 3, id: 'foreign', agentName: 'other', goal: 'waiting', repo: process.cwd(), state: 'needs_human', manifest, itemProgress: [{ itemId: 'item-001', status: 'waiting', phase: 'implementation', cycle: 1, attempt: 0, evidenceReceipts: [], reviewReceipts: [], findings: [], updatedAt: new Date(0).toISOString() }], attempt: 0, maxAttempts: 3, acceptanceChecks: [], artifacts: [], events: [], createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() }; await other.create(foreign); const pty: any = new CodexAppServerPTY({ ...env, ctxRoot: root }, agent); pty.goalRunStore = own; pty.replyLocal = vi.fn(); try { await pty.handleGoalClear('../other/foreign'); await pty.handleGoalResume('../other/foreign'); await pty.handleGoalClear('foreign'); await pty.handleGoalResume('foreign'); expect((await other.get('other', 'foreign'))?.state).toBe('needs_human'); expect(pty.replyLocal.mock.calls.map((call: string[]) => call[0]).join('\n')).toContain('Invalid goal run identifier'); } finally { rmSync(root, { recursive: true, force: true }); } });
  it('uses the persisted worktree for goal thread creation and resume', async () => { const root = mkdtempSync(`${tmpdir()}/goal-worktree-`); const stateRoot = join(root, 'state', 'agent'); const manifest = createGoalManifest('worktree item', ['proof']); const run: GoalRun = { schemaVersion: 3, id: 'worktree', agentName: 'agent', goal: 'worktree item', repo: '/wrong/repo', worktree: process.cwd(), state: 'queued', manifest, itemProgress: [{ itemId: 'item-001', status: 'runnable', phase: 'implementation', cycle: 1, attempt: 0, implementationThreadId: 'persisted-implementation', evidenceReceipts: [], reviewReceipts: [], findings: [], updatedAt: new Date(0).toISOString() }], attempt: 0, maxAttempts: 3, acceptanceChecks: [{ id: 'proof', command: [process.execPath, '-e', 'process.exit(0)'], timeoutMs: 1000, required: true }], artifacts: [], events: [], createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() }; const store = new GoalRunStore(stateRoot, DEFAULT_GOAL_CONFIG); await store.initialize(); await store.create(run); const pty: any = new CodexAppServerPTY({ ...env, ctxRoot: root }, { ...agent, working_directory: '/interactive/cwd' }); let turn = 0; pty.request = vi.fn(async (method: string, params: any) => { if (method === 'thread/start') return { result: { thread: { id: 'review-thread' } } }; if (method === 'turn/start') { const turnId = `turn-${++turn}`; const report = params.input[0].text.includes('Independently review') ? { kind: 'review_report', itemId: 'item-001', cycle: 1, decision: 'approved', summary: 'ok' } : { kind: 'implementation_report', itemId: 'item-001', cycle: 1, status: 'completed', summary: 'done' }; setImmediate(() => { pty.handleRpcMessage({ method: 'item/completed', params: { threadId: params.threadId, turnId, item: { type: 'agentMessage', text: JSON.stringify(report), threadId: params.threadId, turnId } } }); pty.handleRpcMessage({ method: 'turn/completed', params: { threadId: params.threadId, turnId, turn: { id: turnId, threadId: params.threadId, status: 'completed' } } }); }); return { result: { turn: { id: turnId } } }; } return { result: {} }; }); try { await pty.initializeGoalIntegration(); await pty.goalTickPromise; const locations = pty.request.mock.calls.filter(([method]: [string]) => method === 'thread/start' || method === 'thread/resume').map(([, params]: [string, any]) => params.cwd); expect(locations).toEqual([process.cwd(), process.cwd()]); } finally { await pty.kill(); rmSync(root, { recursive: true, force: true }); } });
  it('real initialization advances a persisted run on startup without enqueue or manual signal', async () => {
    const root = mkdtempSync(`${tmpdir()}/goal-pty-startup-`); const stateRoot = join(root, 'state', 'agent'); const manifest = createGoalManifest('startup item', ['proof']);
    const run: GoalRun = { schemaVersion: 3, id: 'startup', agentName: 'agent', goal: 'startup item', repo: process.cwd(), state: 'queued', manifest, itemProgress: [{ itemId: 'item-001', status: 'runnable', phase: 'implementation', cycle: 1, attempt: 0, evidenceReceipts: [], reviewReceipts: [], findings: [], updatedAt: new Date(0).toISOString() }], schedulingCursor: 0, attempt: 0, maxAttempts: 3, acceptanceChecks: [{ id: 'proof', command: [process.execPath, '-e', 'process.exit(0)'], timeoutMs: 1000, required: true }], artifacts: [], events: [], createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() };
    const store = new GoalRunStore(stateRoot, DEFAULT_GOAL_CONFIG); await store.initialize(); await store.create(run);
    const pty: any = new CodexAppServerPTY({ ...env, ctxRoot: root }, agent); let thread = 0; let turn = 0;
    pty.request = vi.fn(async (method: string, params: any) => {
      if (method === 'thread/start') return { result: { thread: { id: `thread-${++thread}` } } };
      if (method === 'turn/start') { const prompt = params.input[0].text as string; const turnId = `turn-${++turn}`; const report = prompt.includes('Independently review') ? { kind: 'review_report', itemId: 'item-001', cycle: 1, decision: 'approved', summary: 'approved' } : { kind: 'implementation_report', itemId: 'item-001', cycle: 1, status: 'completed', summary: 'implemented' }; setImmediate(() => { pty.handleRpcMessage({ method: 'item/completed', params: { threadId: params.threadId, turnId, item: { type: 'agentMessage', text: JSON.stringify(report), threadId: params.threadId, turnId } } }); pty.handleRpcMessage({ method: 'turn/completed', params: { threadId: params.threadId, turnId, turn: { id: turnId, threadId: params.threadId, status: 'completed' } } }); }); return { result: { turn: { id: turnId } } }; }
      return { result: {} };
    });
    try { await pty.initializeGoalIntegration(); await pty.goalTickPromise; expect((await store.get('agent', 'startup'))?.state).toBe('done'); } finally { await pty.kill(); rmSync(root, { recursive: true, force: true }); }
  });
  it('real initialization owns a periodic recovery timer', async () => {
    vi.useFakeTimers(); const root = mkdtempSync(`${tmpdir()}/goal-pty-periodic-`); const previous = process.env.CXR_GOAL_TICK_INTERVAL_MS; process.env.CXR_GOAL_TICK_INTERVAL_MS = '5'; const tick = vi.spyOn(GoalRunner.prototype, 'processTick').mockResolvedValue(); const pty: any = new CodexAppServerPTY({ ...env, ctxRoot: root }, agent);
    try { await pty.initializeGoalIntegration(); await Promise.resolve(); expect(tick).toHaveBeenCalledTimes(1); await vi.advanceTimersByTimeAsync(5); expect(tick.mock.calls.length).toBeGreaterThanOrEqual(2); await pty.stopGoalScheduler(); }
    finally { tick.mockRestore(); if (previous === undefined) delete process.env.CXR_GOAL_TICK_INTERVAL_MS; else process.env.CXR_GOAL_TICK_INTERVAL_MS = previous; vi.useRealTimers(); rmSync(root, { recursive: true, force: true }); }
  });
  it('correlates durable reports/completion to the exact thread and turn and queues ordinary input', async () => { const pty: any = new CodexAppServerPTY(env, agent); pty.goalPendingTurn = { threadId: 'goal-thread', turnId: 'goal-turn', reportText: '' }; pty._executing = true; pty._activeTurnId = 'goal-turn'; pty.queueTurn([{ type: 'text', text: 'ordinary' }]); expect(pty._turnQueue).toHaveLength(1); const completion = pty.createTurnCompletion(1000); pty.handleRpcMessage({ method: 'item/completed', params: { threadId: 'ordinary-thread', turnId: 'ordinary-turn', item: { type: 'agentMessage', text: 'wrong' } } }); pty.handleRpcMessage({ method: 'turn/completed', params: { threadId: 'ordinary-thread', turnId: 'ordinary-turn', turn: { id: 'ordinary-turn', status: 'completed' } } }); expect(pty.goalPendingTurn.reportText).toBe(''); expect(pty._turnCompletion).not.toBeNull(); pty.handleRpcMessage({ method: 'item/completed', params: { threadId: 'goal-thread', turnId: 'goal-turn', item: { type: 'agentMessage', text: 'right' } } }); pty.handleRpcMessage({ method: 'turn/completed', params: { threadId: 'goal-thread', turnId: 'goal-turn', turn: { id: 'goal-turn', threadId: 'goal-thread', status: 'completed' } } }); await completion; expect(pty.goalPendingTurn.reportText).toBe('right'); });
  it('bounds shutdown and cancels a stuck scheduler tick', async () => { vi.useFakeTimers(); const pty: any = new CodexAppServerPTY(env, agent); const shutdown = vi.fn(); pty.goalRunner = { processTick: vi.fn(() => new Promise<void>(() => {})), shutdown }; pty._rpc = { close: vi.fn() }; pty.signalGoalTick(); const stopping = pty.kill(); expect(shutdown).toHaveBeenCalledOnce(); await vi.advanceTimersByTimeAsync(5_000); await stopping; expect(pty._rpc).toBeNull(); vi.useRealTimers(); });
  it('persists an interrupted active goal as retryable before RPC teardown', async () => { const root = mkdtempSync(`${tmpdir()}/goal-pty-shutdown-`); const stateRoot = join(root, 'state', 'agent'); const manifest = createGoalManifest('interrupt', ['proof']); const value: GoalRun = { schemaVersion: 3, id: 'interrupt', agentName: 'agent', goal: 'interrupt', repo: process.cwd(), state: 'queued', manifest, itemProgress: [{ itemId: 'item-001', status: 'runnable', phase: 'implementation', cycle: 1, attempt: 0, evidenceReceipts: [], reviewReceipts: [], findings: [], updatedAt: new Date().toISOString() }], attempt: 0, maxAttempts: 3, acceptanceChecks: [{ id: 'proof', command: [process.execPath, '-e', 'process.exit(0)'], timeoutMs: 1000, required: true }], artifacts: [], events: [], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; const store = new GoalRunStore(stateRoot, DEFAULT_GOAL_CONFIG); await store.initialize(); await store.create(value); const pty: any = new CodexAppServerPTY({ ...env, ctxRoot: root }, agent); const close = vi.fn(); pty._rpc = { close }; pty.request = vi.fn(async (method: string) => method === 'thread/start' ? { result: { thread: { id: 'implementation' } } } : method === 'turn/start' ? { result: { turn: { id: 'stuck-turn' } } } : { result: {} }); try { await pty.initializeGoalIntegration(); for (let index = 0; index < 100 && !pty.goalPendingTurn; index += 1) await new Promise((resolve) => setTimeout(resolve, 1)); expect(pty.goalPendingTurn?.turnId).toBe('stuck-turn'); await pty.kill(); expect(close).toHaveBeenCalledOnce(); expect((await store.get('agent', 'interrupt'))?.state).toBe('retry_wait'); } finally { rmSync(root, { recursive: true, force: true }); } });
});
