import { randomUUID } from 'node:crypto';
import { spawn } from 'node:child_process';
import { auditGoalCompletion } from './goal-manifest.js';
import type { GoalArtifact, GoalCheckResult, GoalConfig, GoalEvidenceReceipt, GoalManifestItem, GoalRun } from './goal-run.js';

const truncateUtf8 = (value: string, maxBytes: number): string => { let bytes = 0; let end = 0; for (const character of value) { const width = Buffer.byteLength(character); if (bytes + width > maxBytes) break; bytes += width; end += character.length; } return value.slice(0, end); };
const redact = (value: string, max: number) => truncateUtf8(value.replace(/-----BEGIN [^-]+-----[\s\S]*?-----END [^-]+-----/g, '[redacted]').replace(/\b(?:Bearer|Basic)\s+[^\s"']+/gi, '[redacted]').replace(/\b(?:sk-[A-Za-z0-9_-]+|gh[pousr]_[A-Za-z0-9_]+|github_pat_[A-Za-z0-9_]+|xox[baprs]-[A-Za-z0-9-]+|AKIA[A-Z0-9]{16})\b/g, '[redacted]').replace(/((?:api[_-]?key|access[_-]?token|refresh[_-]?token|client[_-]?secret|password|secret|token)\s*(?:[:=]\s*|["']?\s*:\s*["']?))[^\s,}"']+/gi, '$1[redacted]'), max);
export class GoalVerifier {
  constructor(private readonly config: GoalConfig, private readonly clock: () => number = Date.now) {}
  async verifyItem(run: GoalRun, item: GoalManifestItem, cycle: number, signal?: AbortSignal): Promise<{ passed: boolean; results: GoalCheckResult[]; artifacts: GoalArtifact[]; receipts: GoalEvidenceReceipt[] }> {
    const requiredIds = new Set(item.evidenceRequirements.map((requirement) => requirement.checkId));
    const selected = run.acceptanceChecks.filter((check) => requiredIds.has(check.id) || check.itemIds?.includes(item.id));
    const execution = await this.executeChecks(run, selected, item.id, cycle, signal);
    const resultById = new Map(execution.results.map((result) => [result.checkId, result]));
    const missing = item.evidenceRequirements.filter((requirement) => requirement.required && !resultById.has(requirement.checkId));
    for (const requirement of missing) execution.results.push({ checkId: requirement.checkId, command: [], passed: false, exitCode: null, signal: null, classification: 'missing_result', durationMs: 0, timestamp: new Date(this.clock()).toISOString(), itemId: item.id, cycle });
    const timestamp = new Date(this.clock()).toISOString(); const artifactsByCheck = (checkId: string) => execution.artifacts.filter((artifact) => artifact.metadata?.checkId === checkId).map((artifact) => artifact.id);
    const receipts = execution.results.map((result) => ({ itemId: item.id, cycle, checkId: result.checkId, passed: result.passed, result, artifactIds: artifactsByCheck(result.checkId), timestamp }));
    const required = item.evidenceRequirements.filter((requirement) => requirement.required);
    return { ...execution, receipts, passed: required.length > 0 && required.every((requirement) => resultById.get(requirement.checkId)?.passed === true) };
  }
  async verify(run: GoalRun, signal?: AbortSignal): Promise<{ passed: boolean; results: GoalCheckResult[]; artifacts: GoalArtifact[] }> { return this.executeChecks(run, run.acceptanceChecks, undefined, undefined, signal); }
  verifyFinal(run: GoalRun): { passed: boolean; errors: string[] } { return auditGoalCompletion(run); }
  private async executeChecks(run: GoalRun, checks: GoalRun['acceptanceChecks'], itemId?: string, cycle?: number, signal?: AbortSignal): Promise<{ passed: boolean; results: GoalCheckResult[]; artifacts: GoalArtifact[] }> {
    const results: GoalCheckResult[] = []; const artifacts: GoalArtifact[] = [];
    for (const check of checks) { if (signal?.aborted) { results.push({ checkId: check.id, command: check.command, passed: false, exitCode: null, signal: 'SIGTERM', classification: 'timeout', durationMs: 0, timestamp: new Date(this.clock()).toISOString(), itemId, cycle }); continue; } const value = await this.execute(check.command, check.timeoutMs || this.config.checkTimeoutMs, run.worktree || run.repo, run.retention?.maxInlineArtifactBytes ?? this.config.maxInlineArtifactBytes, check.id, itemId, cycle, signal); results.push(value.result); artifacts.push(...value.artifacts); }
    let retained = 0; const totalCap = run.retention?.maxArtifactBytes ?? this.config.maxArtifactBytes;
    const bounded = artifacts.map((artifact) => { if (!artifact.content) return artifact; const remaining = Math.max(0, totalCap - retained); const content = truncateUtf8(artifact.content, remaining); retained += Buffer.byteLength(content); return content === artifact.content ? artifact : { ...artifact, content, metadata: { ...artifact.metadata, truncated: true, aggregateTruncated: true } }; }).filter((artifact) => artifact.content !== '' || !artifact.content);
    return { passed: results.every((result) => !checks.find((check) => check.id === result.checkId)?.required || result.passed), results, artifacts: bounded };
  }
  private execute(command: string[], timeoutMs: number, cwd: string, max: number, checkId: string, itemId?: string, cycle?: number, abortSignal?: AbortSignal): Promise<{ result: GoalCheckResult; artifacts: GoalArtifact[] }> {
    const started = Date.now(); if (!command.length) return Promise.resolve({ result: { checkId, command, passed: false, exitCode: null, signal: null, classification: 'spawn_error', durationMs: 0, timestamp: new Date(this.clock()).toISOString(), itemId, cycle }, artifacts: [] });
    return new Promise((resolve) => { let stdout = ''; let stderr = ''; let stdoutTruncated = false; let stderrTruncated = false; let timedOut = false; let settled = false; let killTimer: ReturnType<typeof setTimeout> | undefined; let settleTimer: ReturnType<typeof setTimeout> | undefined; let pendingClose: { code: number | null; signal: NodeJS.Signals | null } | undefined;
      const append = (current: string, data: unknown, mark: () => void): string => { const text = String(data); const next = truncateUtf8(`${current}${text}`, max); if (Buffer.byteLength(next) < Buffer.byteLength(current + text)) mark(); return next; };
      const complete = (exitCode: number | null, signal: NodeJS.Signals | null, classification: GoalCheckResult['classification']) => { if (settled) return; settled = true; if (killTimer) clearTimeout(killTimer); if (settleTimer) clearTimeout(settleTimer); const timestamp = new Date(this.clock()).toISOString(); const artifact = (type: 'stdout' | 'stderr', content: string, truncated: boolean): GoalArtifact | undefined => content ? { id: randomUUID(), type, content: redact(content, max), timestamp, metadata: { checkId, itemId, cycle, truncated } } : undefined; const out = artifact('stdout', stdout, stdoutTruncated); const err = artifact('stderr', stderr, stderrTruncated); resolve({ result: { checkId, command, passed: classification === 'passed', exitCode, signal, classification, durationMs: Date.now() - started, timestamp, stdoutArtifact: out?.id, stderrArtifact: err?.id, itemId, cycle }, artifacts: [out, err].filter((entry): entry is GoalArtifact => Boolean(entry)) }); };
      let child; try { child = spawn(command[0]!, command.slice(1), { cwd, shell: false, detached: process.platform !== 'win32', stdio: ['ignore', 'pipe', 'pipe'] }); } catch { complete(null, null, 'spawn_error'); return; }
      const signalGroup = (signal: NodeJS.Signals) => { try { if (process.platform !== 'win32' && child.pid) process.kill(-child.pid, signal); else child.kill(signal); } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ESRCH') child.kill(signal); } };
      const abort = () => { if (timedOut || settled) return; timedOut = true; signalGroup('SIGTERM'); killTimer = setTimeout(() => { signalGroup('SIGKILL'); killTimer = undefined; if (pendingClose) complete(pendingClose.code, pendingClose.signal, 'timeout'); else { settleTimer = setTimeout(() => complete(null, 'SIGKILL', 'timeout'), 250); } }, 250); }; abortSignal?.addEventListener('abort', abort, { once: true });
      const timer = setTimeout(abort, timeoutMs); child.stdout.on('data', (data) => { stdout = append(stdout, data, () => { stdoutTruncated = true; }); }); child.stderr.on('data', (data) => { stderr = append(stderr, data, () => { stderrTruncated = true; }); }); child.on('error', () => { clearTimeout(timer); abortSignal?.removeEventListener('abort', abort); if (timedOut && killTimer) { pendingClose = { code: null, signal: null }; return; } complete(null, null, timedOut ? 'timeout' : 'spawn_error'); }); child.on('close', (code, signal) => { clearTimeout(timer); abortSignal?.removeEventListener('abort', abort); if (timedOut && killTimer) { pendingClose = { code, signal }; return; } complete(code, signal, timedOut ? 'timeout' : code === 0 ? 'passed' : 'failed'); });
    });
  }
}
